### ISSUE TITLE
Opentype ligatures

### ISSUE THREAD

**Issue by bleemayer** [clauseggers/Playfair-Display#1]
On the regular font the ligatures ct and st seen to be not working properly in the otf, at least in my Mac's font book. I can't see the arc between those letters. Plus, if you could add the long s symbol (old-style s) it will be great. Thanks for the great work.

**Comment by clauseggers** [comment]
You have to enable the `DLIG` feature to render them.

**Comment by bleemayer** [comment]
I've tried with +dlig and same result. The problem is that when I install the otf font the ligatures ct and st loose the arc, so they look like the regular ct and st. I don't now why this happens, but it does not with the ttf version. What about the long s?

**Comment by clauseggers** [comment]
It must be a problem on your end. Have you downloaded the fonts from this repository? If no please do so.

**Comment by bleemayer** [comment]
From this repository. Yes, my guess is Apple's font installer fault. But this problem only happens with this font, that's why I contacted you.

**Comment by clauseggers** [comment]
Do you have the issue in TextEdit? If not then it is an issue with the particular application you are using.

**Comment by bleemayer** [comment]
Tried, no ligatures.

**Comment by clauseggers** [comment]
Try deleting the font caches:
https://glyphsapp.com/tutorials/eliminating-font-cache-problems

**Comment by bleemayer** [comment]
Haha it worked! Thanks very much for the help. By the way, planing to add the long s?
