### ISSUE TITLE
Complete language support for all 98%+ languages

### ISSUE THREAD

**Issue by davelab6** [clauseggers/Playfair-Display#10]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters according to Unicode CLDR :)

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Hungarian (hu) | 131/133 | 98 | \u27e8 (⟨), \u27e9 (⟩) |
| Uzbek (uz) | 86/87 | 98 | \u02bb (ʻ) |

**Comment by clauseggers** [comment]
The first two we already discussed. They are for math typesetting and have nothing to do with Hungarian.

I have added the u02bb.

**Comment by davelab6** [comment]
@sascha do you know how to find out why those 2 were added for Hungarian?

**Comment by fitojb** [comment]
The angular brackets are also useful [in linguistics](https://en.wiktionary.org/wiki/⟨_⟩), but I agree that they are not exclusive to Hungarian :)
