### ISSUE TITLE
Improve Vietnamese

### ISSUE THREAD

**Issue by crystaltype** [clauseggers/Playfair-Display#11]
Some suggestions:

![screen shot 11-10-17 at 06 45 pm](https://user-images.githubusercontent.com/20129845/32733506-070f9012-c8c2-11e7-86f8-1b37f9e08c0e.PNG)
![screen shot 11-10-17 at 06 53 pm](https://user-images.githubusercontent.com/20129845/32733507-074903d8-c8c2-11e7-87a9-20d2b4adee5f.PNG)

- Overall accents are too big. This is a display typeface so it’d lose its elegant when viewed in large sizes. - They should be smaller/narrower. Especially the hookabove, the breve, and the circumflex.
- The hookabove is being scaled vertically (which shouldn't be, it should be resized, keeping the original ratio/weight instead)
- The horn in U/O need to be changed, the dot in it is a little bit too big. 
Here is my suggested changes:
![screen shot 11-13-17 at 10 04 pm](https://user-images.githubusercontent.com/20129845/32732312-c229db0e-c8be-11e7-9e50-a5aaf28b4236.PNG)

![untitled-1](https://user-images.githubusercontent.com/20129845/32732212-75f34a18-c8be-11e7-98e0-0bbc58ea1279.png)
- The lower stem of the horn shouldn’t be pulled horizontally too long, especially in the Ohorn/ohorn. 

I'm willing to help contribute the changes directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate.

Or, you can make changes and then push your work to master and I will give further feedback :)

**Comment by davelab6** [comment]
@clauseggers please integrate this

**Comment by clauseggers** [comment]
Done (a long time ago).
