### ISSUE TITLE
Size of numbers

### ISSUE THREAD

**Issue by My6UoT9** [clauseggers/Playfair-Display#13]
The sizes of numbers 0-9 varies quite much.
While in the example image, there are examples of different numbers. 
- 82° looks same when I write it
- §2· 5 looks different, that charachter "2" is not available it seems.

All in all this makes numbers looks strange.
like 20% 

![pdg](https://user-images.githubusercontent.com/22345162/35106845-3a37b612-fc67-11e7-8d9c-ef15dde07606.PNG)

I tried by download the ttf font from here, and tested in Word .. made no difference.

Is this intended? I mean it certain number combinations look great - despite different size.
But not all combinations, especially when mathematical signs are add.

**Comment by jacobp100** [comment]
We're also having this issue - old style nums is the default setting.

Google Fonts strips out all OpenType features, so I can't enable lining nums via CSS. I can use a version of the font from somewhere else, but even with flattening opentype features, subsetting, I can't get it to be anywhere close to as small as Google Fonts gets it 😔

What do you think about making lining nums the default?

**Comment by RuixiZhang42** [comment]
I’m not quite sure about making lining+tabular numbers the default (well, lining perhaps, but tabular?). As the name “Display” suggests:

> I think [Playfair Display] makes an excellent font for titles and headlines (especially the beautiful italic), however, for long stretches of body copy the delicate, high-contrast strokes might hinder readability, especially when used at smaller sizes. — Quote from [Typewolf](https://www.typewolf.com/site-of-the-day/fonts/playfair-display)

> As the name indicates, Playfair Display is well suited for titling and headlines. — Quote from [Mana Habibian](https://medium.com/@manahabibian/playfair-display-a-typographic-specimen-b311856700bd)

**Comment by jacobp100** [comment]
I was only suggesting making lining numbers default. Tabular numbers shouldn’t be a default

**Comment by RuixiZhang42** [comment]
@jacobp100 I see. The OP had the rather confusing term “size” and also had an emphasis on usage in the context of math. I&nbsp;then conclude that “same size in math” corresponds to “lining+tabular”, since math fonts usually (and should always) make lining+tabular numbers the default.

**Comment by My6UoT9** [comment]
Yes I used the term "size" wrongly.
I looked up lining/tabular, in those words it would be "proportional lining" what I am looking for.

[Defining Old Style, Lining, Proportional, and Tabular Figures](https://www.lifewire.com/how-to-typeset-numbers-1077695)

**Comment by clauseggers** [comment]
These are not Playfair issues. Closed.
