### ISSUE TITLE
spacing and size failure in PDF

### ISSUE THREAD

**Issue by repatt** [clauseggers/Playfair-Display#19]
Dear Claus,
The letter spacing and font size of Playfair-Display Bold (as downloaded in OTF from https://www.ctan.org/tex-archive/fonts/playfair/opentype on 2019-01-20) seems to be different across PDF viewers. This failure also appeared in print. 

I enclosed a photo of a part of the printed version of the PDF file below. The characters appeared approximately twice as big as in the PDF, also touching each other.
[playfair_display_issue.pdf](https://github.com/clauseggers/Playfair-Display/files/2853362/playfair_display_issue.pdf)
![playfair_display_issue](https://user-images.githubusercontent.com/12149563/52599125-078a1380-2e58-11e9-8d9d-ebeb124031d1.jpg)

PDF viewers that display my specimen correctly:
* Okular (Version 0.25.0, KDE Dev. Platform 4.14.22, Linux Mint KDE)
* Firefox 65.0 (64-bit) for Linux Mint
* Hancom PDF Viewer on Android 4.4.2
* Overleaf online preview

PDF viewers that display my specimen incorrectly, reproducing the failure on the photo:
* Adobe Acrobat 17.0 on Android 4.4.2
* unknown software at the publishers workshop

The PDF was generated from TeX source on [overleaf.com](https://www.overleaf.com), using XeLaTeX compiler.
Font import from uploaded OTF:
```
\usepackage{anyfontsize}
\usepackage{soulutf8} % \so{} for spaced out text
\usepackage{fontspec}
\newfontfamily{\pfd}[
    Path = ./,
    Extension = .otf,
    UprightFont = *-Regular,
    BoldFont = *-Bold,
    ItalicFont = *-Black,
]{PlayfairDisplay}
``` 
The problematic text was the result of:
```
{\fontsize{22}{20}\selectfont\textcolor{RedViolet}{\pfd\textbf{\so{TÁNCMŰHELY}}}}\\[2em]
```
This issue seemed to be specific to Playfair Display (all weights), other Didone fonts from [LaTeX font catalogue](http://www.tug.dk/FontCatalogue/seriffontscategorised.html) were displayed correctly with the same settings and context, in the same problematic PDF viewers (printing has not been tested yet with other fonts).

Please inform me if you know some solution or workaround for this problem, or if additional details are required to find the bug.
Best regards,
  Attila

**Comment by clauseggers** [comment]
This is not a Playfair issue.
