### ISSUE TITLE
russian glyphs are completely different from the one hosted on google fonts

### ISSUE THREAD

**Issue by sandrodz** [clauseggers/Playfair-Display#2]
Google fonts hosted PlayfairDIsplay has an issue with `Ы` its reversed.
So I had to use version of the font from this repo which has `Ы` fixed.

Unfortunately glyphs in Russian from this repo look completely different.

from this repo:
<img width="205" alt="screen shot 2017-03-16 at 11 33 56 am" src="https://cloud.githubusercontent.com/assets/8479569/23986211/7ba9b0be-0a3c-11e7-8627-690116e77e18.png">

google fonts:
<img width="207" alt="screen shot 2017-03-16 at 11 34 05 am" src="https://cloud.githubusercontent.com/assets/8479569/23986226/8782114c-0a3c-11e7-9fb7-fc268fdf44e8.png">

English on the other hand is identical:

<img width="181" alt="screen shot 2017-03-16 at 11 35 25 am" src="https://cloud.githubusercontent.com/assets/8479569/23986255/ad884e7e-0a3c-11e7-971b-506e71fd9cfd.png">
<img width="193" alt="screen shot 2017-03-16 at 11 35 30 am" src="https://cloud.githubusercontent.com/assets/8479569/23986256/ad88a2a2-0a3c-11e7-9f4a-6a2a86faf00b.png">

**Comment by clauseggers** [comment]
You haven’t specified Playfair Display as your font in your first example, hence it defaults to Times Roman.

**Comment by sandrodz** [comment]
@clauseggers Hi, I'm pretty sure I've specified correct font in css. Since it works for English, and doesn't work for Russian, it makes me think maybe font downloaded from this repo don't include Russian glyphs? How do I check this?

**Comment by sandrodz** [comment]
here is the simple test of my theory:

<img width="315" alt="screen shot 2017-03-16 at 12 26 09 pm" src="https://cloud.githubusercontent.com/assets/8479569/23987601/cf2b865c-0a43-11e7-98d2-6b157793cb75.png">

**Comment by clauseggers** [comment]
I have no idea what the issue might be, but it is not related to Playfair Display so I’m closing and locking this thread. Good luck.
