### ISSUE TITLE
/tcedilla in Needlpoint Black SemiExpanded

### ISSUE THREAD

**Issue by Aleksamul** [clauseggers/Playfair-Display#21]
The /cedillacomb component doesn't reach the /t component in Needlpoint Black SemiExpanded master. The thin diagonal stroke of the /cedillacomb cannot be made longer, as in that case it will cross the bottom horizontal of the /s component in /scedilla.
![Screen Shot 2019-11-13 at 13 45 28](https://user-images.githubusercontent.com/17069689/68764955-f7d47100-061b-11ea-92e9-9c63b71cba8f.png)

**Comment by clauseggers** [comment]
Hey Aleksandra. I have a custom _cedillacomb-T.case_ glyph with a longer down stroke. Try and see if that one fixes it, otherwise make a new custom _cedillacomb-t_

**Comment by Aleksamul** [comment]
Hey @clauseggers, it worked, thank you!

**Comment by Aleksamul** [comment]
Hey @clauseggers! I added the /cedillacomb-t after all and replaced with it the /cedillacomb in /tcedilla.

**Comment by clauseggers** [comment]
Cool, just remember to set that glyph to not export.
