### ISSUE TITLE
Fonts are little minor than usual

### ISSUE THREAD

**Issue by lwxbr** [clauseggers/Playfair-Display#23]
Hello, @clauseggers, I compared the fonts that I got from transfonter.org (Transfonter is a service where you upload your ttf and it gives your the other file formats you need, as you may know, Google Fonts only let you download the ttf format).

The reason I came to this repository is because the font is breaking in Google Chrome of Mac OSX, I don't know if is because of Transfonter.

 I don't know why the fonts of this repository and from Transfonter are different if they are the same font. Maybe you can help me, thank you!

See for yourself the test I did comparing them:

https://lwxbr.github.io/font-playfair-display-sample/

PS.: The font of this repository is represented in the right column, the left column are the fonts of transfonter.org, the ttf source file of conversion is from Google Fonts.

**Comment by clauseggers** [comment]
As I just told you I don’t offer technical support. This repo is for design specific issues.
