### ISSUE TITLE
Glyph review

### ISSUE THREAD

**Issue by m4rc1e** [clauseggers/Playfair-Display#6]
@clauseggers Just some minor issues to deal with

**Black Italic**
**Dot accent positioning**
![screen shot 2017-11-02 at 20 12 30](https://user-images.githubusercontent.com/7525512/32348052-88f0c7ec-c00a-11e7-9c06-2eea5d239c1a.png)
![screen shot 2017-11-02 at 20 12 17](https://user-images.githubusercontent.com/7525512/32348054-890df268-c00a-11e7-81c0-641993ba3cb5.png)
![screen shot 2017-11-02 at 20 12 08](https://user-images.githubusercontent.com/7525512/32348055-8929abca-c00a-11e7-9240-66242324cb71.png)

**Italic**
Glyph should look like this:
![screen shot 2017-11-02 at 20 08 07](https://user-images.githubusercontent.com/7525512/32348085-9a521bda-c00a-11e7-86a9-94620f318919.png)

but its top accent is missing
![screen shot 2017-11-02 at 20 08 02](https://user-images.githubusercontent.com/7525512/32348117-b19fb2ca-c00a-11e7-8702-b9b90d27c13f.png)

**Comment by m4rc1e** [comment]
I'll have another look tomorrow so don't regen the fonts.

**Comment by clauseggers** [comment]
Fixed
