### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by Tural** [clauseggers/Playfair-Display#9]
Firstly i would like to thank you for adding the letter "Əə" after my request. We ask you to change the letter Ə. Middle line of ə should be on exactly same horizontal line with H's middle horizontal part. Check the link below: 

1. https://www.dropbox.com/s/kda51z2ci20kcrc/Ekran%20Resmi%202017-11-05%2017.14.31.png

2. capital Ə letter https://www.dropbox.com/s/oky49zfpi5kx6i4/Ekran%20Resmi%202017-11-05%2018.22.12.png

3. small ə letter https://www.dropbox.com/s/wfmql4g4aen43as/letter2.jpg

**Comment by clauseggers** [comment]
Hi Tural. Thank you very much for your very helpful comment. In the rush to get this done I had not looked at this carefully enough. Please have a look at this screenshot and tell me if this is correct. Top line is Latin, bottom line Cyrillic.

https://i.imgur.com/RVVSWH9.png

**Comment by Tural** [comment]
Can you make latin one same as cyrillic one ? I think cyrillic one is better and can be ok for Latin version.

**Comment by clauseggers** [comment]
You are right, since this is for Azerbaijani and not IPA I have made the Latin and Cyrillic ə both like the Cyrillic. Do you have any comments on the italic design (besides lifting the mid-stroke on the upper-case and small-caps)?

**Comment by Tural** [comment]
When I tested this don't a couple of months ago, it showed such italic ə letters: 
 http://fontlar.info/index.php/ready/367-playfair-display or screen https://i.imgur.com/dfgoqpb.png

**Comment by clauseggers** [comment]
That’s interesting – I didn’t design those glyphs. Someone have added those glyphs independently. This is how they look currently: https://i.imgur.com/AZYP5Jz.png

Question is which is the preferred design – this one: https://i.imgur.com/dfgoqpb.png or this one: https://i.imgur.com/AZYP5Jz.png ?

**Comment by Tural** [comment]
Capital ə is ok. But it would be great if you edit lower ə. Getting ə just from rotating e is not good idea. Because it is easily recognizable that it is rotated symbol, not independent symbol. Please check ə in my attached screenshot, it would be great to make exactly same symbol
https://i.imgur.com/dfgoqpb.png

**Comment by clauseggers** [comment]
Oh that was you sketch – I see. I’ll see what I can do.

**Comment by clauseggers** [comment]
This is what I came up with. I think it is sufficiently different from a rotated e, while still being congruent with the general design: https://i.imgur.com/4Ajf3nt.png

**Comment by clauseggers** [comment]
Fixed in release 1.202 https://github.com/clauseggers/Playfair-Display/releases/tag/1.202

**Comment by Tural** [comment]
It is cool.

**Comment by Tural** [comment]
Hi, Claus. I suggets the letter 'ə' should be better like that what do you think?  https://i.imgur.com/6p7d9xA.png

**Comment by clauseggers** [comment]
I’m very keen to get this right, but I had difficulty finding (good) examples of how this glyph is designed. Can you help me by directing me to good examples of how it should look? Preferably in pointed pen / expansion stroke / Transitional style as my design.

**Comment by davelab6** [comment]
@alexeiva do you have any examples? :)

**Comment by alexeiva** [comment]
Schwa may deviate between Latin and Cyrillic in serif styles.

Here is what we did in Lora:
Left — Latin Schwa, Right — Cyrillic schwa

<img width="370" alt="32163767-a09d3b2c-bd72-11e7-8b7a-c2c4c1a4126d" src="https://user-images.githubusercontent.com/16634089/33956526-3d589a4e-e058-11e7-97e7-1f1acf9cc5af.png">

<img width="506" alt="32163769-a10562f6-bd72-11e7-95c7-c4ca73a50a00" src="https://user-images.githubusercontent.com/16634089/33956528-3df53160-e058-11e7-86a6-0ff7621a9579.png">

Azerbaijani uses Latin script, but as I understand from this discussion, the Cyrillic form is preferred as a locl variant. Or is it just a personal preference? Would like to see more examples to treat this as local style.

**Comment by DrELM** [comment]
@alexeiva in Azerbaijan we prefer to make horizontal line of schwa at the middle of character. In your samples it seems like 180° rotated "e". And about the terminal, here it should be look like "a"'s, not like "s"'s.

**Comment by alexeiva** [comment]
@DrELM Thank you for the knowledge, I would like to cite this in our [local features](https://github.com/googlefonts/tools/blob/master/encodings/GF%20Glyph%20Sets/RECOMMENDED.md) documentation.

@clauseggers's original design has sufficient deviation of common Latin vs Cyrillic form. I suggest leaving it as is. This local variant may be placed under `schwa.loclAZE`.

<img width="452" alt="screen shot 2017-12-14 at 12 13 42 pm" src="https://user-images.githubusercontent.com/16634089/33982234-3c87a738-e0c9-11e7-9c4a-707969555ed6.png">
<img width="444" alt="screen shot 2017-12-14 at 12 13 45 pm" src="https://user-images.githubusercontent.com/16634089/33982235-3caf33a2-e0c9-11e7-9afa-a1618bbb7f3f.png">
Sample of common Latin Schwa in Gentium.  (Gentium's Cyrillic schwa is incorrect, it lacks a serif).

**Comment by clauseggers** [comment]
Yes, done.
